  import { Geist, Geist_Mono } from "next/font/google";
  import Header from '../components/layout/Header';
  import Footer from '../components/layout/Footer';
  import ScrollToAnchor from '../utils/ScrollToAnchor';
  import Search_bar from '../components/sections/Search_bar';
  //import "./globals.css"
  //import "../assets/scss/style.scss";
  import "../assets/scss/style_2.scss";
  import {CartProvider} from "../global_quantity/CartContext";
  import {ProductProvider} from "../global_quantity/ProductContext";
  import {SidebarProvider} from "../global_quantity/SidebarContext";
  import SidebarLayer from "../components/sections/partials/SidebarOverlay"
  import 'bootstrap/dist/css/bootstrap.min.css';

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  // You can still define metadata if needed in JavaScript
  export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body >
          <ProductProvider>
            <CartProvider>
            <Header className="invert-color" navPosition="right" />
            <SidebarProvider>
              <SidebarLayer/>
              <main className="site-content">
                
                  
                    
                      {children}
                    
                  
                
              </main>
              <Footer />
              <ScrollToAnchor />
            </SidebarProvider>
            </CartProvider>
          </ProductProvider>
        </body>
      </html>
    );
  }
