 
  import { Geist, Geist_Mono } from "next/font/google";
  import Header from '../components/layout/Header';
  import Footer from '../components/layout/Footer';
  import ScrollToAnchor from '../utils/ScrollToAnchor';
  import Search_bar from '../components/sections/Search_bar';
  //import "./globals.css"
  //import "../assets/scss/style.scss";
  import "../assets/scss/main.scss";
  import {CartProvider} from "../global_quantity/CartContext";
  import {ProductProvider} from "../global_quantity/ProductContext";
  import {SidebarProvider} from "../global_quantity/SidebarContext";
  import 'bootstrap/dist/css/bootstrap.min.css';
  import {AuthProvider} from "../global_quantity/AuthContext";
  import { ProfileProvider } from "../global_quantity/ProfileContext";
  import ProfileOptions from "../components/layout/ProfileOptions";


  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  // You can still define metadata if needed in JavaScript
  export const metadata = {
    title: "BotBloc",
    //description: "Generated by create next app",
  };

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body >
          <AuthProvider>
          <ProductProvider>
            <CartProvider>
            <SidebarProvider>
              <ProfileProvider>
                <Header className="invert-color" navPosition="right" />
                
                      <ProfileOptions/>
                      <main>
                        {children}      
                      </main>
                    
                    <Footer />
                  <ScrollToAnchor />
              </ProfileProvider>
            </SidebarProvider>
            </CartProvider>
          </ProductProvider>
          </AuthProvider>
        </body>
      </html>
    );
  }
